STATIC_LIB_NOINST = libenet.a

SRCS = callbacks.c	\
       host.c		\
       list.c		\
       memory.c		\
       packet.c		\
       peer.c		\
       protocol.c	\
       unix.c		\
       win32.c

include ../buildsys.mk

CPPFLAGS += -Iinclude
